on:
  - workflow_dispatch
  - push
name: Build Images
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: Install dtc
        run: sudo apt-get install -y device-tree-compiler
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3
      - name: Checkout
        uses: actions/checkout@master
        with:
          submodules: true
      - name: Make rootfs
        run: sudo bash ./make_rootfs.sh
      - name: Build with Luckfox SDK
        run: bash ./build.sh
      - name: Zip output
        run: bash ./zip_output.sh
      - name: Upload zip to release
        uses: softprops/action-gh-release@v2
        with:
          files: pico-alpine.zip
          fail_on_unmatched_files: true
